### PR TITLE
Fix linear velocity in odometry frame

### PR DESCRIPTION
**Pull request by RobinAbrahamse**
The transform for velocity transformation (=rotation) was inverted, I fixed that. Moreover, the angular velocity is not affected by the transform and thus I removed it. Tested on hardware.

### CODE REVIEW

**Comment by tbolin** [comment]
@RobinAbrahamse 
> Moreover, the angular velocity is not affected by the transform and thus I removed it

This sounds dubious to me. Could you motivate?

**Comment by RobinAbrahamse** [comment]
> This sounds dubious to me. Could you motivate?

Since the transform is linear, it only concerns a rotation. That affects the linear velocity (describing vehicle longitudinal and latitudinal velocity rather than velocity in the map frame) but not the angular velocity. In other words, whether the odometry frame is at a certain angle with respect to the map frame does not affect the rate at which the rotation occurs. We have also confirmed this empirically but it has been a while so I don't have the figures ready now.

**Comment by tbolin** [comment]
@RobinAbrahamse 
I'm a bit confused by the names of the reference frames you are using. You are talking about the rotation of the odometry frame relative to the map frame. There should only be one fixed frame here, given by *header.frame_id*, (and one moving frame, given by *child_frame_id*) and usually both *map* and *odom(etry)* are fixed frames. I'm going to assume that *odometry* is intended to be the moving frame.

Then I don't see how the rotational rate can be independent of which frame that it is represented in. For example: If a tracked body is put on its side so the Y-axis of the moving frame is pointing upwards in the fixed frame, and the body is then rotated counter clockwise, that would result in a positive rotational rate around the Y-axis in the body frame, but a rotational rate around the Z-axis in the fixed frame. 
Since the twist part of the odometry message should be relative to the moving frame the rotational rate in the message should be around the Y-axis in this case. I'm not sure that the rotational rate is not already in the moving frame due to some quirk of the estimation procedure, and therefore does not need to be rotated.

**Comment by RobinAbrahamse** [comment]
I'm inclined to agree with you. I don't remember the details since it has been several months since I looked into this and I mostly remember not seeing a difference between having the transform and not. Now, I no longer use it but might it come up in the next month then I'll check it, otherwise it is out of my scope. Most importantly, the linear velocities are completely useless without the transform inversion.

**Comment by tbolin** [comment]
Ok, I'll merge this PR now then. The linear velocities are likely a lot more important for most applications than the rotational rates.
Let me know if you find anything about the transform for the rotational rates.

**Pull request merged**
